name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

      
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up React.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
      - name: Update sudo
        run: |
          sudo apt-get update
          sudo pip3 install linode-cli
          linode-cli --version  # Verify installation

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 139.162.134.90 >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Run Docker Compose on Linode
        run: |
          ssh -tt root@139.162.134.90 << EOF
            set -e
            cd /root/frontend_gogrok
            git pull origin master
            docker-compose down --volumes
            docker-compose up -d --build
          EOF

  linode-verify:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Install Linode CLI
        run: |
          sudo apt-get update
          sudo pip3 install linode-cli

      - name: Run Linode CLI command
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_TOKEN }} 
        run: |
          linode-cli linodes ls
